### PR TITLE
reducing image quality and res for event images

### LINKED ISSUE #120: Image resolutions
1. Write a python script which can always **resize a picture to a fixed height while maintaining the aspect ratio** This would be the height of the container which we use to display the images in our events page or elsewhere. It can take size as the input. We of course want to keep the original picture somewhere in backup.

2. Use these images in the slideshow on events tab. Make sure that the original image is large enough that after resizing, the width is greater or equal to the width of the container. If greater, you can symetrically clip the image on both ends (left and right). This is a simple CSS thing.

### PR DESCRIPTION
**Pull request by cheekujodhpur**
Temporarily running the command

`mogrify -resize 500x500\> -quality 60% *.jpg` reduced size from 60 MB to 1.6 MB, and the images look as good as needed.

In future, we might want to have something like a CDN on the server and have all images uploaded through an interface which runs these kinda things automatically. It is a big problem to store a 5000x5000 image when it is not at all needed.

Partially fixes #120

### CODE REVIEW

**Comment by TheFlash98** [comment]
Why are there 5 commits again? This time there's a new branch as well.

**Comment by cheekujodhpur** [comment]
I am not sure, but I want to see this in action soon. So I am merging this and pushing to production after I do a few checks.

**Comment by TheFlash98** [comment]
Look good! @nihal111 comments?

**Comment by TheFlash98** [comment]
@cheekujodhpur go ahead and merge this?

**Comment by nihal111** [comment]
Closing with permission.

**Pull request closed without merging**
