### PR TITLE
Competitive Coding: Week 1 Update

### PR DESCRIPTION
**Pull request by frankestein123toinfinity**
Lemme know if any pains

### CODE REVIEW

**Comment by TheFlash98** [comment]
Looks good

**Comment by TheFlash98** [comment]
@frankestein123toinfinity you've been pushing all your commits to master hence every PR you send has so many commits. Although it works, try making a new branch every time you have to send a PR, push to that branch and once it's merged, delete the branch!

**Comment by frankestein123toinfinity** [comment]
Noted.
Thanks for the Tip!

**Comment by TheFlash98** [comment]
😄

**Pull request merged**
