### PR TITLE
Added FOSSEE Front End Development updates for week 2 and week 3(partial)

### PR DESCRIPTION
**Pull request by grubdragon**
Sorry for the delay, not my fault, added updates for week 2 and 3(bonus :stuck_out_tongue: )

### CODE REVIEW

**Comment by TheFlash98** [comment]
Looks good to me!

**Comment by TheFlash98** [comment]
I don't think doing weight wise sorting is a good idea. Rest looks good!

**Comment by grubdragon** [comment]
Okay skipped for now

**Comment by nihal111** [comment]
Thanks, merging 😄

**Pull request merged**
