### PR TITLE
Emoji detector project added

### PR DESCRIPTION
**Pull request by starlord1311**
Emoji detector project added

### CODE REVIEW

**Comment by thenotsodarkknight** [comment]
Why is the entire project added again? (As seen in the Files Changed?)

**Comment by starlord1311** [comment]
I am not sure how that happened. I just added one project. Anyone got any clue?

**Comment by grubdragon** [comment]
You can use something like `git status` to get the files changed, staged for commit etc. Please use it aplenty.

**Comment by grubdragon** [comment]
As for your problem, it might be a GitHub desktop problem

**Comment by TheFlash98** [comment]
Yep, something is wrong here. Can you tell me the exact things you did @starlord1311 ? Can't merge this PR as it might break something.

**Pull request closed without merging**
