### PR TITLE
Updated mentee list for functional programming

### PR DESCRIPTION
**Pull request by sahil00199**

### CODE REVIEW

**Comment by cheekujodhpur** [comment]
@nihal111 Are you busy these days or is there a problem with this PR? In the latter case, I'd like to know. Otherwise, I can merge this.

**Comment by nihal111** [comment]
@cheekujodhpur This PR is left unmerged because for 1- there is the mysterious commit by [shit](https://www.github.com/shit). 2- It should only contain one line removal. (Adarsh Kumar removed from the mentee list).

**Comment by sahil00199** [comment]
Offline the commit had just one deletion. When I push 'shit' screws things up

**Comment by TheFlash98** [comment]
Don't think this can be merged. Send a new PR @sahil00199 :)

**Pull request closed without merging**
