### PR TITLE
Added links to Upcoming Events and Added Git 101 Event

### PR DESCRIPTION
**Pull request by thenotsodarkknight**
1)Facebook Link for ITSP 2018
2)WnCC Web Page link (which is to be updated) for SoC 2018
3)Added Git 101 Event Images.
4)Added Git 101 Event poster.
5)Added Git 101 Event.
Deleted the previous PR by mistake. 
Just Beginner Things. :/

### CODE REVIEW

**Comment by grubdragon** [comment]
Should've used a different PR for the coming soon links. Keep PRs simple, and try to not have too many commits. Building the coming soon thing might have triggered many changes, so..yeah, try to make that one/two commits. Each PR should resolve a single issue ideally.

**Comment by grubdragon** [comment]
Git101 could be another PR. I hope you see what I'm getting at.

**Comment by thenotsodarkknight** [comment]
Yeah. I get it. I had not anticipated the outburst of changes.

**Comment by grubdragon** [comment]
It would help to use `git status` frequently

**Comment by thenotsodarkknight** [comment]
Cool. I'll add 2 different PRs now then. 👍

**Pull request closed without merging**
